name: 'Go Dependency Submission'
description: 'Calculates dependencies for a Go build-target and submits the list to the Dependency Submission API'
author: 'GitHub'
inputs:
  token:
    description: "GitHub Personal Access Token (PAT). Defaults to PAT provided by Action runner"
    required: false
    default: ${{ github.token }}
  metadata:
    required: false
    description: 'User provided map of max key/value pairs of metadata to include with the snapshot e.g. {"lastModified": "12-31-2022"}'
  go-mod-path:
    required: true
    description: 'Repo path to the go.mod file used to detect dependencies for the Go build target. Defaults to go.mod in the root of the repository.'
    default: 'go.mod'
  go-build-target:
    required: true
    description: 'Build target to detect build dependencies. If unspecified, will use "all", with will detect all dependencies used in all build targets (including tests and tools).'
    default: 'all'
  ref:
    required: false
    description: 'The git ref to use for the snapshot. Defaults to the ref of the event that triggered the workflow.'
  sha:
    required: false
    description: 'The git sha to use for the snapshot. Defaults to the sha of the event that triggered the workflow.'
runs:
  using: 'node20'
  main: 'dist/index.js'
